# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hGFw_xMCdtYV52ew89W6sy2clUlExDb-
"""

import requests
import json
import pandas as pd

class PROCESS_DATA(object):
  
  #Constructor 
  def __init__(self):
    pass
  
  """
  Function to execute an API request and return the response
  url - API request URL
  success - API request status
  df - the JSON response as a pandas dataframe
  """
  def get_api_response(self, url):
    # Get the API response
    response = requests.get(url)
    # Check if the API request was successful
    if(response.status_code != 200):
      success = False
      df = pd.DataFrame()
    else:
      success = True
      data = response.text
      # Load the response as json data
      json_data = json.loads(data)
      # Convert the json list to a pandas dataframe
      df = pd.DataFrame(json_data)
    return success, df

if __name__=="__main__":
  process_data = PROCESS_DATA()
  success, df = process_data.get_api_response("http://tour-pedia.org/api/getReviewsByPlaceId?placeId=35537")
  print('*******************API Request Status**********************')
  if(success == True): print('Success!') 
  else: print('Failure!')
  print('***************API Response as a Dataframe*****************')
  print(df)